### ISSUE TITLE
CE.vim can modify wrong window when closing asm view

### ISSUE THREAD

**Issue by DuncanMcBain** [ldrumm/compiler-explorer.vim#1]
The HTTP handler can occasionally accidentally write to the wrong buffer's contents when the asm view has already been closed. A small change to see if the buffer still exists should allow it to avoid this scenario, something like:
```diff
diff --git a/autoload/ce.vim b/autoload/ce.vim
index b7e3193..bf5f2e6 100644
--- a/autoload/ce.vim
+++ b/autoload/ce.vim
@@ -315,6 +315,9 @@ func s:CompileDispatchResponseHandler(data)
             let asm_line += 1
         endfor
     endif
+    if s:ce_asm_bufnr ==# ''
+      return
+    endif
     call s:SyncBuffers(s:ce_src_bufnr, s:ce_asm_bufnr, asm_lines, colormap)
 endfunc
 ```
This isn't exhaustively tested, but seems to stop the overwriting happening in most scenarios.

**Comment by ldrumm** [comment]
Thanks. classic race condition. It's probably best that this goes in `s:SyncBuffers` itself as it's not really the responsibility of the HTTP handler to care about window states. I'm happy to patch this, directly if you think that makes sense?

**Comment by DuncanMcBain** [comment]
Works for me!
