### ISSUE TITLE
Some flags from YouCompleteMe cause compilation failure

### ISSUE THREAD

**Issue by kbenzie** [ldrumm/compiler-explorer.vim#4]
Since YouCompleteMe can make use of some clang specific compiler options this can cause compilation failures in AsmView if compiler explorer is using the a GNU compiler. Such flags include but are not limited to:

* `-resource-data=...`
* `-fdiagnostics-color=auto`
* `-fspell-checking`

Related pull request to follow.

**Comment by ldrumm** [comment]
Thanks for the patch. It definitely stops gcc freaking out, and I can confirm this works. I'm not convinced by the hardcoded list of loops, but we can clean that up later.

Merged
